Document request ownership in case TRITONBACKEND_ModelInstanceExecute…
triton-inference-server/backend pull request #31
Opened 2021-08-02 23:49 UTC by tanmayv25

… returns error

fixes #3176

2021-08-02 23:56 UTC, deadeyegoodwin requested changes

2021-08-02 23:56 UTC, deadeyegoodwin commented on README.md
> +for releasing them. Backend must not retain refrences to the requests
"... for releasing them. Therefore, in the case where TRITONBACKEND_ModelInstanceExecute returns an error, the backend must not retain... "

2021-08-02 23:59 UTC, GuanLuo commented on README.md
> +for releasing them. Backend must not retain refrences to the requests
"references"

2021-08-03 00:10 UTC, deadeyegoodwin approved these changes

2021-08-03 00:18 UTC, GuanLuo approved these changes

2021-08-03 00:19 UTC, merged