Extend START, END, READY controls to allow BOOL type
triton-inference-server/backend pull request #34
Opened 2021-08-10 23:27 UTC by krishung5

2021-08-11 00:49 UTC, CoderHam requested changes

2021-08-11 00:49 UTC, CoderHam commented on include/triton/backend/backend_common.h
> +/// the tensor type is int32.
this should be INT32 to be consistent

2021-08-11 00:49 UTC, CoderHam commented on include/triton/backend/backend_common.h
> +/// the tensor type is int32.
Here too

2021-08-11 00:49 UTC, CoderHam commented on src/backend_common.cc
> +                       "sequence batching must not specify neither "
not specify either ... or ...

2021-08-11 01:00 UTC, krishung5 commented on src/backend_common.cc
> +                       "sequence batching must not specify neither "
Updated

2021-08-11 17:00 UTC, CoderHam approved these changes

2021-08-11 17:03 UTC, deadeyegoodwin submitted a review, later dismissed

2021-08-12 20:17 UTC, deadeyegoodwin approved these changes

2021-08-12 20:41 UTC, merged