Improve documentation on decoupled backend API
triton-inference-server/backend pull request #57
Opened 2022-05-09 16:41 UTC by tanmayv25

2022-05-09 17:32 UTC, nv-kmcgill53 commented on README.md
> +executing a single inference requests typically requires the following
"executing a single inference request typically"

2022-05-09 17:33 UTC, nv-kmcgill53 commented on README.md
> +  2. For each output tensor that the request expects to be returned, use
output tensor which the request expects to be returned

2022-05-09 19:32 UTC, nv-kmcgill53 approved these changes

2022-05-10 00:26 UTC, GuanLuo submitted a review, later dismissed

2022-05-10 02:37 UTC, nv-kmcgill53 approved these changes

2022-05-10 16:57 UTC, Tabrizian submitted a review, later dismissed

2022-05-10 19:09 UTC, CoderHam requested changes

2022-05-10 19:09 UTC, CoderHam commented on README.md
> +kind of backend executing a single inference request requires the
nit: backend, executing

2022-05-10 19:09 UTC, CoderHam commented on README.md
> +The decoupled backends use `ResponseFactory` object per request to keep
use one `ResponseFactory` object per request

2022-05-10 19:09 UTC, CoderHam commented on README.md
> +creating and sending any number of responses for the request.  For this
Remove extra space before "For"

2022-05-10 21:33 UTC, CoderHam approved these changes

2022-05-10 21:34 UTC, merged